import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:postgrest/postgrest.dart';
import 'package:project_momentum/services/questwell_open_task_list.dart';
import 'package:project_momentum/services/questwell_task_service.dart';

String taskId(int n) =>
    '00000000-0000-4000-8000-${n.toString().padLeft(12, '0')}';
Map<String, dynamic> task(int n, {bool tied = false}) => {
  'id': taskId(n),
  'user_id': 'owner-a',
  'status': 'open',
  'created_at': DateTime.utc(
    2026,
    1,
    1,
  ).add(Duration(microseconds: tied ? 0 : n)).toIso8601String(),
  'title': 'Quest $n',
  'pinned_at': n == 1 ? '2026-01-01T00:00:00Z' : null,
  'friction_level': 1,
};
http.Response response(Object rows, {int status = 200}) => http.Response(
  jsonEncode(rows),
  status,
  headers: {'content-type': 'application/json'},
);
QuestwellOpenTaskList loader(
  Future<http.Response> Function(http.Request) handle, {
  String? Function()? owner,
}) {
  final client = MockClient((request) async {
    final result = await handle(request);
    return http.Response.bytes(
      result.bodyBytes,
      result.statusCode,
      headers: result.headers,
      request: request,
    );
  });
  addTearDown(client.close);
  return QuestwellOpenTaskList(
    database: PostgrestClient(
      'https://fixture.invalid/rest/v1',
      httpClient: client,
    ),
    currentOwner: owner ?? () => 'owner-a',
  );
}

// Interpret the real PostgREST cursor generated by the loader, not a page index.
List<Map<String, dynamic>> page(
  http.Request request,
  List<Map<String, dynamic>> rows, {
  int serverCap = 37,
}) {
  final q = request.url.queryParameters;
  expect(q['user_id'], 'eq.owner-a');
  expect(q['status'], 'eq.open');
  expect(q['order'], 'created_at.desc.nullslast,id.desc.nullslast');
  expect(q.containsKey('offset'), isFalse);
  var eligible = rows;
  if (q['or'] != null) {
    final match = RegExp(
      r'^\(created_at\.lt\.(.*),and\(created_at\.eq\.(.*),id\.lt\.([^,)]+)\)\)$',
    ).firstMatch(q['or']!);
    expect(match, isNotNull);
    expect(match!.group(1), match.group(2));
    final time = DateTime.parse(match.group(1)!);
    final id = match.group(3)!;
    eligible = rows.where((r) {
      final rowTime = DateTime.parse(r['created_at'] as String);
      return rowTime.isBefore(time) ||
          (rowTime.isAtSameMomentAs(time) &&
              (r['id'] as String).compareTo(id) < 0);
    }).toList();
  }
  final limit = int.parse(q['limit']!);
  return eligible.take(limit < serverCap ? limit : serverCap).toList();
}

void main() {
  test('historical single-page query reproduces 50 of 135 quests', () async {
    final rows = List.generate(135, (i) => task(135 - i));
    final client = MockClient(
      (r) async => http.Response(
        jsonEncode(
          rows.take(int.parse(r.url.queryParameters['limit']!)).toList(),
        ),
        200,
        headers: {'content-type': 'application/json'},
        request: r,
      ),
    );
    addTearDown(client.close);
    final db = PostgrestClient(
      'https://fixture.invalid/rest/v1',
      httpClient: client,
    );
    final truncated = await db
        .from('tasks')
        .select()
        .eq('user_id', 'owner-a')
        .eq('status', 'open')
        .order('created_at', ascending: false)
        .limit(50);
    expect(truncated, hasLength(50));
    expect(truncated.any((r) => r['pinned_at'] != null), isFalse);
  });
  for (final tied in [false, true]) {
    test(
      'all 135 quests and old pin survive capped pages; tied=$tied',
      () async {
        final rows = List.generate(135, (i) => task(135 - i, tied: tied));
        var requests = 0;
        final tasks = await loader((r) async {
          requests++;
          return response(page(r, rows));
        }).load();
        expect(tasks, hasLength(135));
        expect(tasks.map((t) => t.id).toSet(), hasLength(135));
        expect(tasks.last.id, taskId(1));
        expect(requests, 5); // Four data pages, then an empty page.
        expect(
          QuestwellTaskService.visibleHomeTasks(
            tasks,
            campfireMode: true,
          ).single.id,
          taskId(1),
        );
      },
    );
  }
  test(
    'insert/delete before the cursor does not skip remaining quests',
    () async {
      final rows = List.generate(135, (i) => task(135 - i));
      var requests = 0;
      final tasks = await loader((r) async {
        if (++requests == 2) {
          rows.removeAt(0);
          rows.insert(0, task(136));
        }
        return response(page(r, rows));
      }).load();
      expect(
        tasks.map((t) => t.id),
        List.generate(135, (i) => taskId(135 - i)),
      );
    },
  );
  test('microsecond cursor survives web precision and unrelated UUID order', () async {
    var requests = 0;
    final newer = task(1)..['created_at'] = '2026-01-01T00:00:00.000002+00:00';
    final older = task(2)..['created_at'] = '2026-01-01T00:00:00.000001+00:00';
    final tasks = await loader((r) async {
      requests++;
      if (requests == 1) return response([newer]);
      final expected = requests == 2 ? newer : older;
      expect(
        r.url.queryParameters['or'],
        '(created_at.lt.${expected['created_at']},and(created_at.eq.${expected['created_at']},id.lt.${expected['id']}))',
      );
      return response(requests == 2 ? [older] : []);
    }).load();
    expect(tasks.map((t) => t.id), [taskId(1), taskId(2)]);
  });
  test('signed-out list makes no request', () async {
    expect(
      await loader(
        (_) async => throw StateError('unexpected request'),
        owner: () => null,
      ).load(),
      isEmpty,
    );
  });
  test('empty account returns empty list', () async {
    expect(await loader((_) async => response([])).load(), isEmpty);
  });
  test('account switch in flight discards response and stops paging', () async {
    var owner = 'owner-a';
    var requests = 0;
    await expectLater(
      loader((_) async {
        requests++;
        owner = 'owner-b';
        return response([task(1)]);
      }, owner: () => owner).load(),
      throwsStateError,
    );
    expect(requests, 1);
  });
  for (final bad in ['owner', 'status', 'id', 'time', 'duplicate', 'order']) {
    test('invalid $bad fails rather than displaying partial results', () async {
      var requests = 0;
      await expectLater(
        loader((_) async {
          if (++requests == 1) return response([task(3)]);
          final row = task(2);
          switch (bad) {
            case 'owner':
              row['user_id'] = 'owner-b';
              break;
            case 'status':
              row['status'] = 'completed';
              break;
            case 'id':
              row['id'] = 'invalid,cursor';
              break;
            case 'time':
              row['created_at'] = null;
              break;
            case 'duplicate':
              return response([task(3)]);
            case 'order':
              return response([task(4)]);
          }
          return response([row]);
        }).load(),
        throwsStateError,
      );
      expect(requests, 2);
    });
  }
  test(
    'later-page failure fails whole load; a fresh load can recover',
    () async {
      var requests = 0;
      var fail = true;
      final rows = List.generate(135, (i) => task(135 - i));
      final service = loader((r) async {
        if (++requests == 2 && fail) {
          return response({
            'message': 'unavailable',
            'code': 'fixture',
          }, status: 503);
        }
        return response(page(r, rows));
      });
      await expectLater(service.load(), throwsA(isA<PostgrestException>()));
      fail = false;
      requests = 0;
      expect(await service.load(), hasLength(135));
    },
  );
}
