const marketReviewCatalog = <Map<String,dynamic>>[
  {"id": "review-pumpkin-sprite", "slug": "pumpkin-sprite", "name": "Pumpkin Sprite", "category": "familiar", "rarity": "rare", "description": "A bright-eyed little harvest spirit with curling vines and a warm amber glow. Your next small win has company.", "price": 180, "premium": false, "asset_key": "familiar_pumpkin_sprite", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-copper-potion-workbench", "slug": "copper-potion-workbench", "name": "Copper Potion Workbench", "category": "room", "rarity": "uncommon", "description": "A walnut apothecary cabinet with a copper distiller, jewel-toned potions and herb drawers. Place on either side of your Hearth.", "price": 120, "premium": false, "asset_key": "room_copper_potion_workbench", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-midnight-observatory", "slug": "midnight-observatory", "name": "Midnight Observatory", "category": "room", "rarity": "uncommon", "description": "Indigo walls, brass celestial trim and a star-filled window. Changes your Hearth setting; keeps your furniture.", "price": 120, "premium": false, "asset_key": "room_midnight_observatory", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-alchemists-workshop", "slug": "alchemists-workshop", "name": "Alchemist’s Workshop", "category": "room", "rarity": "uncommon", "description": "Plum walls, copper pipes, potion shelves and hanging herbs. Changes your Hearth setting; keeps your furniture.", "price": 120, "premium": false, "asset_key": "room_alchemists_workshop", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-astral-sanctuary", "slug": "astral-sanctuary", "name": "Astral Sanctuary", "category": "room", "rarity": "rare", "description": "Animated crystal shimmer and drifting starlight in a violet sanctuary. Changes your Hearth setting; keeps your furniture.", "price": 300, "premium": false, "asset_key": "room_astral_sanctuary", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-emberglass-conservatory", "slug": "emberglass-conservatory", "name": "Emberglass Conservatory", "category": "room", "rarity": "rare", "description": "Animated golden fireflies among copper glasswork and climbing greenery. Changes your Hearth setting; keeps your furniture.", "price": 300, "premium": false, "asset_key": "room_emberglass_conservatory", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-enchanted-library", "slug": "enchanted-library", "name": "Enchanted Library", "category": "room", "rarity": "uncommon", "description": "Emerald walls, walnut shelves and warm brass lamps for a quiet reading retreat. Changes your Hearth setting; keeps your furniture.", "price": 120, "premium": false, "asset_key": "room_enchanted_library", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-woodland-cottage", "slug": "woodland-cottage", "name": "Woodland Cottage", "category": "room", "rarity": "uncommon", "description": "A moss-green cottage with climbing ivy, warm oak beams and a forest view. Changes your Hearth setting; keeps your furniture.", "price": 120, "premium": false, "asset_key": "room_woodland_cottage", "required_archetype": null, "unlock_method": "shop"},
  {"id": "review-midnight-harvest", "slug": "midnight-harvest", "name": "Midnight Harvest", "category": "room", "rarity": "uncommon", "description": "Copper leaves, amber firelight and a moonlit autumn forest. Changes your Hearth setting; keeps your furniture.", "price": 120, "premium": false, "asset_key": "room_midnight_harvest", "required_archetype": null, "unlock_method": "shop"},

  {
    "id": "review-emerald-wayfarer-rug",
    "slug": "emerald-wayfarer-rug",
    "name": "Emerald Wayfarer Rug",
    "category": "room",
    "rarity": "common",
    "description": "Deep green threads, a woven gold border, and a compass rose. A soft place to begin your next adventure.",
    "price": 20,
    "premium": false,
    "asset_key": "room_emerald_wayfarer_rug",
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "f968c42c-01e1-4eaa-8fc1-626f1d0d3840",
    "slug": "starter-business-suit",
    "name": "Business Suit",
    "category": "chest",
    "rarity": "common",
    "description": "A polished starter look for getting things done.",
    "price": 0,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "b6703520-a26e-42b7-98f8-1283465e8413",
    "slug": "round-scholar-glasses",
    "name": "Round Scholar Glasses",
    "category": "face",
    "rarity": "common",
    "description": "For adventurers who read the footnotes.",
    "price": 40,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "3ecaaff0-4867-429f-aec9-e3568d8b3f9f",
    "slug": "brass-lantern",
    "name": "Brass Lantern",
    "category": "hands",
    "rarity": "uncommon",
    "description": "A warm amber light for the next small step. Brass, candlelight, and a little courage.",
    "price": 60,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "081c1b12-e357-457f-a1e1-42012f68f140",
    "slug": "emerald-scholar-scarf",
    "name": "Emerald Scholar Scarf",
    "category": "neck",
    "rarity": "uncommon",
    "description": "A deep emerald scarf with warm gold trim for the Hearth adventurer.",
    "price": 60,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "0004cda1-263a-41ad-b813-98c3a1973def",
    "slug": "leather-satchel",
    "name": "Leather Satchel",
    "category": "back",
    "rarity": "common",
    "description": "Holds maps, snacks, and unfinished thoughts.",
    "price": 60,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "db4b5226-277b-401d-a96d-ffb69447863e",
    "slug": "moonstone-brooch",
    "name": "Moonstone Brooch",
    "category": "accessory",
    "rarity": "uncommon",
    "description": "A little moonlight for the road ahead. Icy blue stone framed in antique gold.",
    "price": 60,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "b23e43e4-d599-4516-ac6d-49d8ee54908c",
    "slug": "moss-green-cloak",
    "name": "Moss-Green Cloak",
    "category": "chest",
    "rarity": "uncommon",
    "description": "A soft cloak for damp forests and difficult emails.",
    "price": 90,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "b92ac877-90b7-4f54-a476-8e1ae1e0e76c",
    "slug": "burgundy-reading-chair",
    "name": "Burgundy Reading Chair",
    "category": "room",
    "rarity": "uncommon",
    "description": "Burgundy upholstery, walnut legs, and brass studs. Settle in with a good book.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "424e17f5-5311-4ade-889f-0ed8eeef5b5c",
    "slug": "celestial-study",
    "name": "Celestial Study",
    "category": "wall_art",
    "rarity": "uncommon",
    "description": "A golden crescent and constellations against midnight blue. Hang on the left or right wall.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "e05de2a9-ed63-4165-9957-c2aa12a09dcc",
    "slug": "fern-study",
    "name": "Fern Study",
    "category": "wall_art",
    "rarity": "uncommon",
    "description": "A green fern on warm parchment, framed in walnut and gold. Hang on the left or right wall.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "65d80b98-2571-42da-9290-26ca077af465",
    "slug": "hearth-fern",
    "name": "Hearth Fern",
    "category": "room",
    "rarity": "uncommon",
    "description": "Lush green fronds in an aged brass planter. A little life for your Hearth.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "123c9e63-0bc1-4529-96e9-59844a63cb3c",
    "slug": "moonlit-woodland",
    "name": "Moonlit Woodland",
    "category": "wall_art",
    "rarity": "uncommon",
    "description": "A moonlit forest and a warmly lit cottage, framed in walnut and gold. Hang in the center, with room for smaller paintings on either side.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "9616a790-0b25-4126-ad26-f7207221e5bd",
    "slug": "rainy-window",
    "name": "Rainy Window",
    "category": "room",
    "rarity": "uncommon",
    "description": "Permanent cozy weather for The Hearth.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "ed1982c9-e757-4c22-b130-1dabf6fb6117",
    "slug": "walnut-bookshelf",
    "name": "Walnut Bookshelf",
    "category": "room",
    "rarity": "uncommon",
    "description": "Warm walnut, worn jewel-toned books, and brass details. A quiet corner for your Hearth.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "bc945114-68f3-412a-a6a5-fcf3f26811d2",
    "slug": "walnut-reading-table",
    "name": "Walnut Reading Table",
    "category": "room",
    "rarity": "uncommon",
    "description": "Worn books, warm walnut, and candlelight. A quiet companion for your reading chair.",
    "price": 120,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "dbea3aef-4e56-4c04-85a9-6d3f95ecafd6",
    "slug": "tiny-wizard-hat",
    "name": "Tiny Wizard Hat",
    "category": "head",
    "rarity": "rare",
    "description": "Impractical. Essential.",
    "price": 140,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "5eb623ea-cf00-477e-a864-e1f7ab918c4a",
    "slug": "victory-sparkle",
    "name": "Victory Sparkle",
    "category": "effect",
    "rarity": "rare",
    "description": "A little magic when a quest falls.",
    "price": 150,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "0bf520f4-6fa2-4f49-bb28-efbdc76b8cd1",
    "slug": "annotated-grimoire",
    "name": "Annotated Grimoire",
    "category": "hands",
    "rarity": "rare",
    "description": "A margin-filled field guide for people who weaponize footnotes.",
    "price": 160,
    "premium": false,
    "required_archetype": "scholar",
    "unlock_method": "shop"
  },
  {
    "id": "dd545109-eab9-4fa0-9986-ae9fb1d6494a",
    "slug": "focus-tonic",
    "name": "Focus Tonic",
    "category": "effect",
    "rarity": "rare",
    "description": "A suspiciously sparkly reminder that momentum can be brewed.",
    "price": 160,
    "premium": false,
    "required_archetype": "alchemist",
    "unlock_method": "shop"
  },
  {
    "id": "22ced578-b539-46dd-a323-478464bfb03d",
    "slug": "hearthguard-mantle",
    "name": "Hearthguard Mantle",
    "category": "chest",
    "rarity": "rare",
    "description": "Heavy enough to feel protected. Soft enough for a desk chair.",
    "price": 160,
    "premium": false,
    "required_archetype": "guardian",
    "unlock_method": "shop"
  },
  {
    "id": "d3e3ffa7-e48b-4c7c-a236-deb64a0b7943",
    "slug": "pathfinder-boots",
    "name": "Pathfinder Boots",
    "category": "feet",
    "rarity": "rare",
    "description": "For finding the shortest route through a long day.",
    "price": 160,
    "premium": false,
    "required_archetype": "scout",
    "unlock_method": "shop"
  },
  {
    "id": "8c7104b4-3aed-4033-9c11-e1f166dd0ff4",
    "slug": "wayfarer-satchel",
    "name": "Wayfarer Satchel",
    "category": "back",
    "rarity": "rare",
    "description": "Carries three plans, two snacks, and one backup plan.",
    "price": 160,
    "premium": false,
    "required_archetype": "wanderer",
    "unlock_method": "shop"
  },
  {
    "id": "000069e3-894b-4417-8eb3-26d0b0327438",
    "slug": "mushroom-familiar",
    "name": "Mushroom Familiar",
    "category": "familiar",
    "rarity": "rare",
    "description": "A loyal little spore scout.",
    "price": 180,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "ae3c1dcc-9654-42a6-900f-8ece7a322070",
    "slug": "tiny-owl-familiar",
    "name": "Tiny Owl Familiar",
    "category": "familiar",
    "rarity": "epic",
    "description": "Judges your task list with great wisdom.",
    "price": 260,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
  {
    "id": "6972531a-2145-4b03-9d6e-bbfa749fcf94",
    "slug": "archive-owl",
    "name": "Archive Owl",
    "category": "familiar",
    "rarity": "epic",
    "description": "Knows where the file is. Judges you for not using folders.",
    "price": 280,
    "premium": false,
    "required_archetype": "scholar",
    "unlock_method": "shop"
  },
  {
    "id": "e522b74b-d5fd-4284-a4e2-5490fbf700e7",
    "slug": "glass-slime",
    "name": "Glass Slime",
    "category": "familiar",
    "rarity": "epic",
    "description": "A tiny lab assistant with excellent viscosity and no inbox.",
    "price": 280,
    "premium": false,
    "required_archetype": "alchemist",
    "unlock_method": "shop"
  },
  {
    "id": "92d8538f-f0f3-46fe-a3de-6a4b9a63b8d1",
    "slug": "moss-moth",
    "name": "Moss Moth",
    "category": "familiar",
    "rarity": "epic",
    "description": "Follows curiosity. Occasionally lands on the correct task.",
    "price": 280,
    "premium": false,
    "required_archetype": "wanderer",
    "unlock_method": "shop"
  },
  {
    "id": "ac2ec9bb-3b62-4342-a9de-ee66588925db",
    "slug": "signal-fox",
    "name": "Signal Fox",
    "category": "familiar",
    "rarity": "epic",
    "description": "Spots distractions before they become side quests.",
    "price": 280,
    "premium": false,
    "required_archetype": "scout",
    "unlock_method": "shop"
  },
  {
    "id": "00cfdc3f-9947-4f90-8cee-3d83769be92c",
    "slug": "warding-lantern",
    "name": "Warding Lantern",
    "category": "room",
    "rarity": "epic",
    "description": "Keeps the room warm and the unnecessary meeting invites out.",
    "price": 280,
    "premium": false,
    "required_archetype": "guardian",
    "unlock_method": "shop"
  },
  {
    "id": "9beb0f5f-53df-418b-8396-63643937d7d0",
    "slug": "emerald-dragon",
    "name": "Emerald Dragon",
    "category": "familiar",
    "rarity": "epic",
    "description": "A small emerald companion with golden horns and a talent for guarding your next small win.",
    "price": 320,
    "premium": false,
    "required_archetype": null,
    "unlock_method": "shop"
  },
];
