"""Generate matching native and browser visibility paths; never edit pixels."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = json.loads((ROOT / 'tool/wanderer_underlayer_visibility.json').read_text())
rows = []
for body, polygons in spec['bodies'].items():
    rows.append(f"    '{body}': [")
    for polygon in polygons:
        rows.append('      [' + ', '.join(f'Offset({x}, {y})' for x, y in polygon) + '],')
    rows.append('    ],')
dart = """// Generated by tool/generate_wanderer_underlayer.py. Do not edit by hand.
import 'dart:math' as math;
import 'package:flutter/material.dart';

/// Occludes only the original jacket beneath Wanderer. The source base stays intact.
class WandererUnderlayerClipper extends CustomClipper<Path> {
  const WandererUnderlayerClipper(this.bodyType);
  final String bodyType;

  static const _visible = <String, List<List<Offset>>>{
""" + '\n'.join(rows) + """
  };

  @override
  Path getClip(Size size) {
    // Match the base Image's BoxFit.contain and Alignment.bottomCenter exactly.
    final scale = math.min(size.width / 240, size.height / 320);
    final dx = (size.width - 240 * scale) / 2;
    final dy = size.height - 320 * scale;
    final path = Path();
    for (final polygon in _visible[bodyType] ?? _visible['neutral']!) {
      path.moveTo(dx + polygon.first.dx * scale, dy + polygon.first.dy * scale);
      for (final point in polygon.skip(1)) {
        path.lineTo(dx + point.dx * scale, dy + point.dy * scale);
      }
      path.close();
    }
    return path;
  }

  @override
  bool shouldReclip(covariant WandererUnderlayerClipper oldClipper) =>
      oldClipper.bodyType != bodyType;
}
"""
(ROOT / 'lib/widgets/wanderer_underlayer_clip.dart').write_text(dart)
(ROOT / 'web/wanderer-underlayer.js').write_text(
    '// Generated from the same coordinates as the Flutter clipper.\n'
    + 'const wandererUnderlayerVisibility = ' + json.dumps(spec['bodies']) + ';\n')
