const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),sharp=require('sharp');
const root=path.resolve(__dirname,'..'),art=path.join(__dirname,'art_assets/grimoire_belt_v1');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const transparent=()=>sharp({create:{width:240,height:320,channels:4,background:'#00000000'}});
const asset=p=>path.join(root,p),avatar='assets/images/questwell/avatar/';
const placements={female:{anchor:[132,147],book:[126,157,24]},neutral:{anchor:[136,157],book:[130,165,25]},male:{anchor:[137,155],book:[130,164,26]}};
(async()=>{fs.mkdirSync(art,{recursive:true});const bookAsset='assets/images/questwell_annotated_grimoire_v1.webp',bookPng=await sharp(asset(bookAsset)).png().toBuffer();const report={status:'offline_visual_qa_pending',method:'Exact locked neutral/female garment compositing with identical native coordinate placement to Flutter widget. Male shows existing full business-suit base; Flutter runtime shader rendering remains unverified without Flutter.',bookAsset,bookSha256:sha(bookAsset),bookAssetPreserved:true,rotation:.1,validationLimitation:'Flutter tests and runtime rendering cannot be executed locally because Flutter is unavailable. Offline composites validate asset placement; CI and live review remain separate.',bodies:{}};const previews=[];
for(const body of['female','neutral','male']){let layers;if(body==='neutral')layers=[avatar+'classes/scholar/scholar_robe_rear_neutral_v1.webp',avatar+'base/paper_doll_neutral_v4.webp',avatar+'everyday_boots_neutral_v3.webp',avatar+'everyday_trousers_neutral_v3.webp',avatar+'everyday_top_neutral_v3.webp',avatar+'classes/scholar/scholar_robe_neutral_v1.webp',avatar+'base/paper_doll_neutral_identity_v4.webp',avatar+'classes/scholar/scholar_robe_collar_neutral_v1.webp',avatar+'classes/scholar/scholar_robe_cuff_front_neutral_v1.webp'];else if(body==='female')layers=[avatar+'classes/scholar/scholar_robe_rear_female_v3.webp',avatar+'base/paper_doll_female_v1.webp',avatar+'scout_trousers_female_v6.webp',avatar+'scout_top_female_v6.webp',avatar+'scout_boots_female_v6.webp',avatar+'classes/scholar/scholar_robe_female_v3.webp',avatar+'base/paper_doll_female_identity_v1.webp',avatar+'classes/scholar/scholar_robe_cuff_front_female_v3.webp'];else layers=[avatar+'base/base_male.webp'];
const baseline=await transparent().composite(layers.map(p=>({input:asset(p)}))).png().toBuffer();const {anchor:[ax,ay],book:[x,y,w]}=placements[body],h=w*499/356;
const svg=Buffer.from(`<svg width="960" height="1280" viewBox="0 0 240 320" xmlns="http://www.w3.org/2000/svg"><rect x="${ax-3}" y="${ay-1.5}" width="6" height="${y+5-(ay-1.5)}" rx="1.7" fill="#291c13"/><rect x="${ax-2}" y="${ay-.5}" width="4" height="${y+4-(ay-.5)}" rx="1" fill="#765032"/><path d="M${ax-1.5} ${ay+.7}V${y+3}" stroke="#ad8051" stroke-width=".6"/><circle cx="${ax}" cy="${ay+2}" r="1.05" fill="#d0a24e"/><circle cx="${ax-.25}" cy="${ay+1.7}" r=".35" fill="#f3d487"/><g transform="rotate(${.1*180/Math.PI} ${x+w/2} ${y})"><image x="${x}" y="${y}" width="${w}" height="${h}" href="data:image/png;base64,${bookPng.toString('base64')}"/></g></svg>`);
const accessory=await sharp(svg).resize(240,320).png().toBuffer();const final=await sharp(baseline).composite([{input:accessory}]).png().toBuffer();await sharp(final).png().toFile(path.join(art,body+'_native.png'));await sharp(final).resize(720,960).png().toFile(path.join(art,body+'.png'));for(const[name,bg]of[['light','#eee7da'],['dark','#20272e']]){await sharp(final).flatten({background:bg}).resize(480,640).png().toFile(path.join(art,body+'_'+name+'.png'));await sharp(final).flatten({background:bg}).extract({left:110,top:139,width:72,height:72}).resize(576,576).png().toFile(path.join(art,body+'_belt_'+name+'.png'));}
const before=await sharp(baseline).ensureAlpha().raw().toBuffer(),after=await sharp(final).ensureAlpha().raw().toBuffer(), added=await sharp(accessory).ensureAlpha().raw().toBuffer();const hands=body==='female'?[[62,169,88,198],[153,169,180,198]]:[[57,173,89,202],[157,173,184,202]];let changed=0;for(const[l,t,r,b]of hands)for(let yy=t;yy<b;yy++)for(let xx=l;xx<r;xx++){const i=(yy*240+xx)*4;for(let c=0;c<4;c++)if(added[i+3]>0&&before[i+c]!==after[i+c])changed++;}if(changed)throw Error('Accessory intersects hand review area '+body+' '+changed);report.bodies[body]={...placements[body],bookHeight:h,handRegionChangedChannels:changed,sourceAssets:layers.map(p=>({path:p,sha256:sha(p)}))};previews.push({input:await sharp(final).flatten({background:'#eee7da'}).resize(480,640).png().toBuffer(),left:480*previews.length,top:32});}
const labels=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="32"><g font-family="sans-serif" font-size="18" fill="#272523"><text x="20" y="24">Female • fitted Scholar robe</text><text x="500" y="24">Neutral • locked Scholar robe</text><text x="980" y="24">Male • existing base outfit</text></g></svg>');await sharp({create:{width:1440,height:672,channels:4,background:'#eee7da'}}).composite([...previews,{input:labels,left:0,top:0}]).png().toFile(path.join(art,'grimoire_belt_review.png'));fs.writeFileSync(path.join(art,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(Object.fromEntries(Object.entries(report.bodies).map(([k,v])=>[k,{handRegionChangedChannels:v.handRegionChangedChannels}]))));})();
