// Generated by tool/generate_scholar_underlayer.py. Do not edit by hand.
import 'dart:math' as math;
import 'package:flutter/material.dart';

/// Occludes only the original jacket beneath Scholar. The source base stays intact.
class ScholarUnderlayerClipper extends CustomClipper<Path> {
  const ScholarUnderlayerClipper(this.bodyType);
  final String bodyType;

  static const _visible = <String, List<List<Offset>>>{
    'male': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 75), Offset(137, 75), Offset(137, 83), Offset(106, 83), Offset(106, 75), Offset(0, 75)],
      [Offset(106, 75), Offset(137, 75), Offset(137, 139), Offset(143, 149), Offset(143, 162), Offset(105, 162), Offset(106, 144)],
      [Offset(50, 173), Offset(85, 173), Offset(85, 200), Offset(50, 200)],
      [Offset(153, 172), Offset(188, 172), Offset(188, 200), Offset(153, 200)],
      [Offset(104, 155), Offset(143, 155), Offset(145, 180), Offset(153, 200), Offset(240, 200), Offset(240, 320), Offset(0, 320), Offset(0, 200), Offset(92, 200), Offset(100, 180)],
    ],
    'female': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 76), Offset(137, 76), Offset(137, 83), Offset(106, 83), Offset(106, 76), Offset(0, 76)],
      [Offset(65, 70), Offset(107, 70), Offset(103, 82), Offset(93, 86), Offset(86, 100), Offset(84, 115), Offset(68, 115)],
      [Offset(136, 70), Offset(174, 70), Offset(174, 115), Offset(156, 115), Offset(155, 99), Offset(149, 90), Offset(139, 84)],
      [Offset(106, 75), Offset(136, 75), Offset(136, 135), Offset(141, 144), Offset(141, 156), Offset(104, 156), Offset(108, 137)],
      [Offset(58, 168), Offset(87, 168), Offset(87, 195), Offset(58, 195)],
      [Offset(152, 167), Offset(179, 167), Offset(179, 195), Offset(152, 195)],
      [Offset(104, 149), Offset(141, 149), Offset(145, 178), Offset(154, 196), Offset(240, 196), Offset(240, 320), Offset(0, 320), Offset(0, 196), Offset(90, 196), Offset(99, 177)],
    ],
    'neutral': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 76), Offset(138, 76), Offset(138, 84), Offset(106, 84), Offset(106, 76), Offset(0, 76)],
      [Offset(106, 76), Offset(138, 76), Offset(138, 140), Offset(144, 148), Offset(144, 159), Offset(104, 159), Offset(108, 142)],
      [Offset(57, 172), Offset(88, 172), Offset(88, 199), Offset(57, 199)],
      [Offset(152, 172), Offset(184, 172), Offset(184, 199), Offset(152, 199)],
      [Offset(104, 153), Offset(144, 153), Offset(147, 180), Offset(155, 200), Offset(240, 200), Offset(240, 320), Offset(0, 320), Offset(0, 200), Offset(91, 200), Offset(99, 181)],
    ],
  };

  @override
  Path getClip(Size size) {
    // Match the base Image's BoxFit.contain and Alignment.bottomCenter exactly.
    final scale = math.min(size.width / 240, size.height / 320);
    final dx = (size.width - 240 * scale) / 2;
    final dy = size.height - 320 * scale;
    final path = Path();
    for (final polygon in _visible[bodyType] ?? _visible['neutral']!) {
      path.moveTo(dx + polygon.first.dx * scale, dy + polygon.first.dy * scale);
      for (final point in polygon.skip(1)) {
        path.lineTo(dx + point.dx * scale, dy + point.dy * scale);
      }
      path.close();
    }
    return path;
  }

  @override
  bool shouldReclip(covariant ScholarUnderlayerClipper oldClipper) =>
      oldClipper.bodyType != bodyType;
}
