// Generated by tool/generate_scout_underlayer.py. Do not edit by hand.
import 'dart:math' as math;
import 'package:flutter/material.dart';

/// Occludes only the original jacket beneath Scout. The source base stays intact.
class ScoutUnderlayerClipper extends CustomClipper<Path> {
  const ScoutUnderlayerClipper(this.bodyType);
  final String bodyType;

  static const _visible = <String, List<List<Offset>>>{
    'male': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 75), Offset(137, 75), Offset(137, 83), Offset(105, 83), Offset(105, 75), Offset(0, 75)],
      [Offset(105, 75), Offset(137, 75), Offset(137, 140), Offset(141, 150), Offset(141, 160), Offset(105, 160), Offset(106, 142)],
      [Offset(56, 171), Offset(85, 171), Offset(85, 200), Offset(56, 200)],
      [Offset(153, 171), Offset(184, 171), Offset(184, 200), Offset(153, 200)],
      [Offset(105, 154), Offset(141, 154), Offset(145, 180), Offset(154, 200), Offset(240, 200), Offset(240, 320), Offset(0, 320), Offset(0, 200), Offset(92, 200), Offset(101, 179)],
    ],
    'female': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 76), Offset(137, 76), Offset(137, 83), Offset(106, 83), Offset(106, 76), Offset(0, 76)],
      [Offset(65, 70), Offset(107, 70), Offset(106, 82), Offset(93, 86), Offset(86, 100), Offset(84, 117), Offset(68, 117)],
      [Offset(136, 70), Offset(174, 70), Offset(174, 115), Offset(156, 115), Offset(155, 99), Offset(149, 90), Offset(137, 84)],
      [Offset(106, 75), Offset(136, 75), Offset(135, 135), Offset(140, 143), Offset(140, 155), Offset(104, 155), Offset(108, 137)],
      [Offset(62, 167), Offset(87, 167), Offset(87, 195), Offset(62, 195)],
      [Offset(151, 167), Offset(179, 167), Offset(179, 195), Offset(151, 195)],
      [Offset(104, 148), Offset(140, 148), Offset(145, 177), Offset(155, 196), Offset(240, 196), Offset(240, 320), Offset(0, 320), Offset(0, 196), Offset(90, 196), Offset(99, 176)],
    ],
    'neutral': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 76), Offset(138, 76), Offset(138, 84), Offset(106, 84), Offset(106, 76), Offset(0, 76)],
      [Offset(106, 76), Offset(137, 76), Offset(137, 140), Offset(142, 148), Offset(142, 159), Offset(105, 159), Offset(108, 142)],
      [Offset(58, 171), Offset(88, 171), Offset(88, 199), Offset(58, 199)],
      [Offset(152, 171), Offset(183, 171), Offset(183, 199), Offset(152, 199)],
      [Offset(105, 153), Offset(142, 153), Offset(147, 180), Offset(155, 200), Offset(240, 200), Offset(240, 320), Offset(0, 320), Offset(0, 200), Offset(91, 200), Offset(100, 181)],
    ],
  };

  @override
  Path getClip(Size size) {
    // Match the base Image's BoxFit.contain and Alignment.bottomCenter exactly.
    final scale = math.min(size.width / 240, size.height / 320);
    final dx = (size.width - 240 * scale) / 2;
    final dy = size.height - 320 * scale;
    final path = Path();
    for (final polygon in _visible[bodyType] ?? _visible['neutral']!) {
      path.moveTo(dx + polygon.first.dx * scale, dy + polygon.first.dy * scale);
      for (final point in polygon.skip(1)) {
        path.lineTo(dx + point.dx * scale, dy + point.dy * scale);
      }
      path.close();
    }
    return path;
  }

  @override
  bool shouldReclip(covariant ScoutUnderlayerClipper oldClipper) =>
      oldClipper.bodyType != bodyType;
}
