// Generated by tool/generate_wanderer_underlayer.py. Do not edit by hand.
import 'dart:math' as math;
import 'package:flutter/material.dart';

/// Occludes only the original jacket beneath Wanderer. The source base stays intact.
class WandererUnderlayerClipper extends CustomClipper<Path> {
  const WandererUnderlayerClipper(this.bodyType);
  final String bodyType;

  static const _visible = <String, List<List<Offset>>>{
    'male': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 75), Offset(137, 75), Offset(137, 83), Offset(105, 83), Offset(105, 75), Offset(0, 75)],
      [Offset(105, 75), Offset(137, 75), Offset(136, 138), Offset(140, 150), Offset(140, 160), Offset(106, 160), Offset(107, 142)],
      [Offset(64, 171), Offset(79, 171), Offset(82, 178), Offset(85, 183), Offset(85, 200), Offset(56, 200), Offset(56, 181), Offset(62, 176)],
      [Offset(158, 171), Offset(179, 171), Offset(184, 200), Offset(153, 200), Offset(153, 183), Offset(157, 176)],
      [Offset(106, 154), Offset(140, 154), Offset(145, 180), Offset(154, 200), Offset(240, 200), Offset(240, 320), Offset(0, 320), Offset(0, 200), Offset(92, 200), Offset(101, 179)],
    ],
    'female': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 76), Offset(137, 76), Offset(137, 83), Offset(106, 83), Offset(106, 76), Offset(0, 76)],
      [Offset(65, 70), Offset(107, 70), Offset(106, 82), Offset(93, 86), Offset(86, 100), Offset(84, 117), Offset(68, 117)],
      [Offset(136, 70), Offset(174, 70), Offset(174, 115), Offset(156, 115), Offset(155, 99), Offset(149, 90), Offset(137, 84)],
      [Offset(107, 75), Offset(135, 75), Offset(135, 135), Offset(140, 143), Offset(140, 155), Offset(105, 155), Offset(109, 137)],
      [Offset(62, 167), Offset(87, 167), Offset(87, 195), Offset(62, 195)],
      [Offset(151, 167), Offset(179, 167), Offset(179, 195), Offset(151, 195)],
      [Offset(105, 148), Offset(140, 148), Offset(145, 177), Offset(155, 196), Offset(240, 196), Offset(240, 320), Offset(0, 320), Offset(0, 196), Offset(90, 196), Offset(99, 176)],
    ],
    'neutral': [
      [Offset(0, 0), Offset(240, 0), Offset(240, 76), Offset(138, 76), Offset(138, 84), Offset(106, 84), Offset(106, 76), Offset(0, 76)],
      [Offset(107, 76), Offset(137, 76), Offset(136, 140), Offset(141, 148), Offset(141, 159), Offset(106, 159), Offset(109, 142)],
      [Offset(65, 171), Offset(80, 171), Offset(84, 178), Offset(88, 183), Offset(88, 199), Offset(58, 199), Offset(58, 184), Offset(64, 178)],
      [Offset(157, 171), Offset(177, 171), Offset(183, 199), Offset(152, 199), Offset(152, 182), Offset(156, 177)],
      [Offset(106, 153), Offset(141, 153), Offset(147, 180), Offset(155, 200), Offset(240, 200), Offset(240, 320), Offset(0, 320), Offset(0, 200), Offset(91, 200), Offset(100, 181)],
    ],
  };

  @override
  Path getClip(Size size) {
    // Match the base Image's BoxFit.contain and Alignment.bottomCenter exactly.
    final scale = math.min(size.width / 240, size.height / 320);
    final dx = (size.width - 240 * scale) / 2;
    final dy = size.height - 320 * scale;
    final path = Path();
    for (final polygon in _visible[bodyType] ?? _visible['neutral']!) {
      path.moveTo(dx + polygon.first.dx * scale, dy + polygon.first.dy * scale);
      for (final point in polygon.skip(1)) {
        path.lineTo(dx + point.dx * scale, dy + point.dy * scale);
      }
      path.close();
    }
    return path;
  }

  @override
  bool shouldReclip(covariant WandererUnderlayerClipper oldClipper) =>
      oldClipper.bodyType != bodyType;
}
